% run_snr_sweep.m
% Sum Rate Baseline:
% Perfect-CSI AO vs Estimated-CSI AO (TRUE evaluation)
%
% Phase 2 baseline experiment.
%
% Prerequisite:
%   py results/export_channels_snr_sweep.py
%
% Run this script from project root.

clear; close all; clc;

% Reduced noise sweep for faster Phase 2 experimentation
noise_dbm_sweep = [-100, -92.5, -85, -77.5, -70];

% Reduced Monte Carlo realizations
n_realizations = 3;

n_pts = length(noise_dbm_sweep);

snr_db = zeros(1, n_pts);

sumrate_perfect_mean = zeros(1, n_pts);
sumrate_perfect_std  = zeros(1, n_pts);

sumrate_est_mean = zeros(1, n_pts);
sumrate_est_std  = zeros(1, n_pts);


for i = 1:n_pts

    noise_dbm = noise_dbm_sweep(i);

    rp = zeros(1, n_realizations);
    re = zeros(1, n_realizations);
    snr_trials = zeros(1, n_realizations);


    for trial = 0:n_realizations-1

        fprintf('Noise %.1f dBm | Trial %d/%d\n', ...
            noise_dbm, trial + 1, n_realizations);

        fname = sprintf( ...
            'results/snr_sweep/phase2_data_snr%s_trial%d.mat', ...
            strrep(num2str(noise_dbm), '.', 'p'), ...
            trial);

        % For negative decimal values, use the exact filename
        % generated by Python.
        fname = sprintf( ...
            'results/snr_sweep/phase2_data_snr%.1f_trial%d.mat', ...
            noise_dbm, trial);

        % Integer noise values have filenames without ".0"
        if mod(noise_dbm, 1) == 0
            fname = sprintf( ...
                'results/snr_sweep/phase2_data_snr%d_trial%d.mat', ...
                noise_dbm, trial);
        end

        d = load(fname);

        M = double(d.M);
        N = double(d.N);
        K = double(d.K);

        P_max = double(d.P_max);
        sigma = double(d.sigma);

        H_true = d.H_true;
        G_true = d.G_true;

        C_hat = d.C_hat;


        %% ---------------------------------------------------------
        % 1. Perfect-CSI AO
        % ----------------------------------------------------------

        rng(1);

        [SumRate_perfect, ~, ~] = ...
            Opt_func_perfectCSI( ...
                M, N, K, P_max, sigma, ...
                H_true, G_true);


        %% ---------------------------------------------------------
        % 2. Estimated-CSI AO
        %
        % AO uses estimated cascaded channel C_hat.
        % Final performance is evaluated on TRUE H/G.
        % ----------------------------------------------------------

        rng(1);

        [~, P_estCk, Theta_estCk] = ...
            Opt_func_Ck( ...
                M, N, K, P_max, sigma, C_hat);

        Phi_est = diag(conj(Theta_estCk));

        H_all_true_eval = ...
            H_true' * Phi_est * G_true;

        SumRate_estCk_trueEval = ...
            compute_sum_rate( ...
                H_all_true_eval, ...
                P_estCk, ...
                K, ...
                sigma);


        %% ---------------------------------------------------------
        % 3. Reference Received SNR
        %
        % Use the actual cascaded BS -> IRS -> User channel.
        %
        % A neutral IRS configuration is used for the
        % reference SNR so that the x-axis does not depend
        % on either AO algorithm.
        % ----------------------------------------------------------

        Phi_ref = eye(M);

        H_eff_ref = ...
            H_true' * Phi_ref * G_true;

        % Equal transmit power across BS antennas
        P_ant = P_max / N;

        % Average received signal power across users
        P_rx_ref = ...
            P_ant * mean( ...
                sum(abs(H_eff_ref).^2, 2));

        snr_trials(trial + 1) = ...
            10 * log10(P_rx_ref / sigma);


        %% Store results

        rp(trial + 1) = SumRate_perfect;

        re(trial + 1) = ...
            SumRate_estCk_trueEval;

    end


    %% Average across channel realizations

    snr_db(i) = mean(snr_trials);

    sumrate_perfect_mean(i) = mean(rp);
    sumrate_perfect_std(i)  = std(rp);

    sumrate_est_mean(i) = mean(re);
    sumrate_est_std(i)  = std(re);


    fprintf( ...
    'noise=%.1f dBm | Reference SNR=%.1f dB | Perfect=%.2f+-%.2f | Estimated(true)=%.2f+-%.2f bps/Hz\n\n', ...
    noise_dbm, ...
    snr_db(i), ...
    sumrate_perfect_mean(i), ...
    sumrate_perfect_std(i), ...
    sumrate_est_mean(i), ...
    sumrate_est_std(i));

end


%% Save results

save( ...
    'results/snr_sweep_results.mat', ...
    'snr_db', ...
    'sumrate_perfect_mean', ...
    'sumrate_perfect_std', ...
    'sumrate_est_mean', ...
    'sumrate_est_std', ...
    'noise_dbm_sweep');


fprintf('\nSaved results/snr_sweep_results.mat\n');


%% Plot

[snr_sorted, idx] = sort(snr_db);

figure( ...
    'Position', ...
    [100, 100, 750, 550]);


errorbar( ...
    snr_sorted, ...
    sumrate_perfect_mean(idx), ...
    sumrate_perfect_std(idx), ...
    'o-', ...
    'LineWidth', 2, ...
    'MarkerSize', 7, ...
    'Color', [0.2 0.6 0.2]);

hold on;


errorbar( ...
    snr_sorted, ...
    sumrate_est_mean(idx), ...
    sumrate_est_std(idx), ...
    's-', ...
    'LineWidth', 2, ...
    'MarkerSize', 7, ...
    'Color', [0.85 0.33 0.1]);


xlabel('Reference Received SNR (dB)');
ylabel('Sum Rate (bps/Hz)');

title( ...
    'Phase 2 Baseline: Perfect-CSI AO vs Estimated-CSI AO');


legend( ...
    'Perfect-CSI AO (ideal-CSI reference)', ...
    'Estimated-CSI AO (classical)', ...
    'Location', ...
    'best');

grid on;


saveas( ...
    gcf, ...
    'results/fig_sumrate_baseline.png');


fprintf( ...
    'Saved results/fig_sumrate_baseline.png\n');


%% ---------------------------------------------------------------
% Local function: Sum Rate
% ---------------------------------------------------------------

function R = compute_sum_rate(H_all, P, K, sigma)

    R = 0;

    for k = 1:K

        % Desired signal power
        S = abs(H_all(k,:) * P(:,k))^2;

        % Multi-user interference
        IN = 0;

        for j = 1:K

            if j == k
                continue;
            end

            IN = IN + ...
                abs(H_all(k,:) * P(:,j))^2;

        end

        % User k rate
        R = R + ...
            log2(1 + S / (IN + sigma));

    end

end